---
title: "Archaeology"
output: html_notebook
---

```{r}
library(cowplot)
library(dplyr)
library(ggplot2)
library(devtools)
#install_github("oswaldosantos/ggsn")
#library(ggsn)
library(ggrepel)
library(ggthemes)
library(raster)
library(reshape2)
library(rgdal)
library(sp)
library(viridis)
```


## Set up geodata

```{r}
# bounding box
xmin <- -10
xmax <- 10
ymin <- 5
ymax <- 22

epsg <- 4326
crs <- paste("+init=epsg:",epsg,"", sep="")

cnt <- spTransform(readOGR(dsn = "../data/vector", layer="10m_admin_0_countries", verbose = FALSE), CRS( crs))
rvr <- spTransform(readOGR(dsn = "../data/vector", layer="10m_rivers_lake_centerlines", verbose = FALSE), CRS(crs))

# raster layer with rainforest cover from bioval.jrc.ec.europa.eu
dpath <- "../data/raster/bioval.jrc.ec.europa.eu/hdr.adf"
x <- new("GDALReadOnlyDataset", dpath)
getDriver(x)
getDriverLongName(getDriver(x))

hdr <- asSGDF_GROD(x)
hdr <- raster(hdr)

# extent format (xmin,xmax,ymin,ymax)
e  <- extent(6, 23, -8.5, 8.5) 
rfs <- crop(hdr, e) 

# convert the raster to points for plotting
rfs.p <- rasterToPoints(rfs)

# Make the points a dataframe for ggplot & subset rainforest bands 1-7
rfs.d <- data.frame(rfs.p)
rfs.d <- subset(rfs.d, band1 >= 1 & band1 <= 7)

# create the breaks- and label vectors; see https://stackoverflow.com/a/33302968
ewbrks <- seq(ymin,ymax,5)
nsbrks <- seq(xmin,xmax,5)
ewlbls <- unlist(lapply(ewbrks, function(x) ifelse(x < 0, paste(x, "째E"), ifelse(x > 0, paste(x, "째W"),x))))
nslbls <- unlist(lapply(nsbrks, function(x) ifelse(x < 0, paste(x, "째S"), ifelse(x > 0, paste(x, "째N"),x))))

# Create basemap
g.b <- ggplot() + 
  geom_polygon(data = cnt, 
              aes(long, lat, group = group, fill=hole),
              fill  = "#ffebbe") + 
  geom_raster(data = rfs.d, aes(y = y, x = x), fill = '#00734d') + 
  geom_polygon(data = cnt, 
              aes(long, lat, group = group),
              size = 0.2, 
              fill  = NA,  
              color = "black") + 
  geom_path(data = rvr, 
            aes(long, lat, group = group, fill=NULL),
            size = 0.5,   
            colour  = "#44afe3") + 
  #scalebar(location = "bottomright", dist = 250, height = 0.2,
  #         dd2km = TRUE, model = 'WGS84',           
  #         x.min = 15, x.max = 22,
  #         y.min = -6.25, y.max = -5.25, 
  #         st.dist = .4, st.size = 4) +
  scale_x_continuous("", 
                     breaks = ewbrks, 
                     labels = ewlbls) +
  scale_y_continuous("", 
                     breaks = nsbrks, 
                     labels = nslbls) +
  coord_equal(xlim=c(7, 22),
              ylim=c(-7.5,7.5)) + 
  theme_few() + 
  theme(panel.background = element_rect(fill = "#dff1f9"),
        plot.background = element_rect(color = NA, 
                                       fill = NA)
  )

# the minimap:
csl <- spTransform(readOGR(dsn = "../data/vector", layer="ne_110m_land", verbose = FALSE), CRS( crs))

g2 <- ggplotGrob(
  ggplot() + 
  geom_path(data = csl, 
               aes(long, lat, group = group),
               size = 0.2, 
               fill = 'white', color = "black") + 
  geom_rect(mapping = aes(xmin = 6.5, xmax = 22.5, 
                          ymin = -8, ymax = 8), 
            alpha = 0.5, fill ="black", size = 0.5) + 
  coord_equal() + 
  scale_x_continuous(limits = c(-20, 55), expand = c(0, 0)) + 
  scale_y_continuous(limits = c(-40, 42), expand = c(0, 0)) + 
  theme_map() + 
  theme(panel.background = element_rect(fill = 'white'), 
        panel.border = element_rect(colour  = 'black', fill = NA, size = 1))
)
```

```{r}
d <- read.csv("https://raw.githubusercontent.com/dirkseidensticker/aDRAC/master/data/aDRAC.csv", encoding = "UTF-8")

# filter rough bounding box
d <- filter(d, LAT < xmax & 
              LAT > xmin & 
              LONG > ymin & 
              LONG < ymax &
              C14AGE >= 15 & 
              C14AGE <= 3000 & 
              C14STD < 200 &
              PHASE != "LSA" &
              ((REL != 0) | (is.na(d$REL))))
# REL != 0

d$dummy <- 'maxAge'

s <- dcast(d, SITE + LAT + LONG ~ dummy, 
               value.var = "C14AGE", 
               fun.aggregate = max)
```

### Paleoecology sites

```{r}
p <- read.csv("../data/base/Hubau2015sites.csv")
```

### Hubs from Linguistics (Bostoen et al. 2015: 359 Fig. 2)

```{r}
l <- read.csv("../data/base/Bostoen2015_359Fig2_BantuHubs.csv")
```

### Labels for archaeological Sites

```{r}
a.labs <- read.csv("../data/base/ArchSitesLabs.csv", encoding = "UTF-8")
```

### Map with dated sites, age as fill
```{r}
g1 <- g.b + 
  geom_point(data = s %>% arrange(maxAge), 
             aes(x = LONG,
                 y = LAT,
                 fill = cut(maxAge, c(3001, 
                                      2750, 
                                      2500, 
                                      2250, 
                                      2000, 
                                      1000, 
                                      0))),
             shape = 21, 
             size = 3, 
             color = 'grey',
             stroke = .25) + 
  scale_fill_viridis(option = "C", 
                     direction = -1, 
                     discrete = T,
                     labels=c("AD 1000-1950",
                              "BC/AD-AD 1000",
                              "250 BC-BC/AD", 
                              "500-250 BC", 
                              "750-500 BC",
                              "1000-750 BC", 
                              "")) + 
  geom_point(aes(x = 10.077778, 
                 y = 5.8586611), 
             shape = 23,
             size = 3, 
             fill = 'red', 
             color = 'grey',
             stroke = .25) + 
  geom_point(data = p, 
             aes(x = Longitude, 
                 y = Latitude), 
             shape = 23,
             size = 3,
             color = 'black',
             fill = 'white') +
  geom_point(data = l, 
             aes(x = long, 
                 y = lat), 
             shape = 22,
             size = 7,
             fill = 'lightgray',
             color = 'white',
             alpha = 0.75) +
  geom_text(data = l, 
            aes(x = long, 
               y = lat, 
               label = node), 
            size = 4) + 
  # geom_label_repel(data = a.labs, 
  #                  aes(x = LONG,
  #                      y = LAT,
  #                      label = SITE),
  #                  label.size = NA,
  #                  label.padding = unit(.1, "lines"),
  #                  size = 2,
  #                  segment.color = 'black', 
  #                  segment.size = .1,
  #                  min.segment.length = unit(0, "lines")) + 
  # geom_label_repel(data = p, 
  #                  aes(x = Longitude,
  #                      y = Latitude,
  #                      label = Name),
  #                  label.size = NA,
  #                  label.padding = unit(.1, "lines"),
  #                  size = 2,
  #                  segment.color = 'black',
  #                  segment.size = .1,
  #                  min.segment.length = unit(0, "lines"),
  #                  fill = "grey30",
  #                  colour = "white", 
  #                  fontface = "bold") + 
  guides(fill = guide_legend(reverse = T,
                             ncol = 2)) + 
  theme(legend.title = element_blank(), 
        legend.justification = c(1, 1), 
        legend.position = c(.995, .995))

g3 <- g1 + 
  annotation_custom(grob = g2, 
                    xmin = 6, xmax = 10,
                    ymin = -8, ymax = -4)
g3
ggsave(g3, filename = "../img/FigArch-A_map.pdf", 
       width = 8, height = 8)
```

### OxCal

```{r}
  library(oxcAAR)
quickSetupOxcal()
#setOxcalExecutablePath("OxCal")
my_dates <- R_Date(d$LABNR, d$C14AGE, d$C14STD)
my_sum <- oxcal_Sum(my_dates)

write(my_sum, file = "../data/processed/Sum.txt")
```

> run in OxCal an Export "Raw data"

```{r}
sum <- read.table(file = "../data/processed/Sum.prior")

p2 <- ggplot(sum, aes(x = V1, y = V2)) + 
  geom_area(fill = '#666666') + 
  scale_x_continuous("Age (cal BC/AD)", 
                     limits = c(-1000, 1950), 
                     breaks = seq(-1000, 1950, by = 250), 
                     expand = c(0,0)) + 
  scale_y_continuous("Prob. Density", 
                     limits = c(0, 0.8), 
                     expand = c(0,0)) + 
  theme_few() +  
  theme(panel.grid.major.x = element_blank(), 
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        plot.background = element_rect(color = NA, 
                                       fill = NA))
p2
```

### Build comined figure

```{r}
p0 <- plot_grid(g3, p2, labels = "AUTO", ncol = 1, align = "v", rel_widths = c(1, 1), rel_heights = c(3, 1))
ggsave("../img//FigArch.pdf", p0, width = 5, height = 8)
p0
```
